import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getServerSideProps() {
    const res = await fetch(
        "https://pokemon-ssr.s3.sa-east-1.amazonaws.com/pokemon-main/index.json"
    );

    return { props: { pokemons: await res.json() } };
}

export default function Home({ pokemons }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Pokemon List</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.grid}>
                {pokemons.map((pokemon) => (
                    <article className={styles.card} key={pokemon.id}>
                        <Link href={`/pokemon/${pokemon.id}`}>
                            <a>
                                <Image
                                    src={`https://pokemon-ssr.s3.sa-east-1.amazonaws.com/pokemon-main/${pokemon.image}`}
                                    alt={pokemon.name}
                                    width={200}
                                    height={200}
                                />
                                <h3>{pokemon.name}</h3>
                            </a>
                        </Link>
                    </article>
                ))}
            </main>
        </div>
    );
}
