import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
    const [pokemons, setPokemons] = useState([]);

    useEffect(() => {
        const getPokemon = async () => {
            const res = await fetch(
                "https://pokemon-ssr.s3.sa-east-1.amazonaws.com/pokemon-main/index.json"
            );
            setPokemons(await res.json());
        };

        getPokemon();
    }, []);
    return (
        <div className={styles.container}>
            <Head>
                <title>Pokemon List</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.grid}>
                {pokemons.map((pokemon) => (
                    <article className={styles.card} key={pokemon.id}>
                        <Link href={`/pokemon/${pokemon.id}`}>
                            <a>
                                <img
                                    src={`https://pokemon-ssr.s3.sa-east-1.amazonaws.com/pokemon-main/${pokemon.image}`}
                                    alt={pokemon.name}
                                />
                                <h3>{pokemon.name}</h3>
                            </a>
                        </Link>
                    </article>
                ))}
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
